const types = {
    SET_MENUDATA: 'SET_MENUDATA',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    TAB_CHANGE: 'TAB_CHANGE',
    KEEP_CHANGE: 'KEEP_CHANGE',
    SET_LOGINSTATUS: 'SET_LOGINSTATUS',
    LOGOUT: 'LOGOUT',
    SET_USERNAME: 'SET_USERNAME',
    SET_TOKEN: 'SET_TOKEN',
    SET_REFRESH_TOKEN: 'SET_REFRESH_TOKEN',
    SET_EXPIRES_TIME: 'SET_EXPIRES_TIME',
};
export default types;
